export const ComponentsTypes = {
    SHOW_DRAWER : 'SHOW_DRAWER',
    CLOSE_DRAWER : 'CLOSE_DRAWER',
    START_LOADING : 'START_LOADING',
    FINISH_LOADING : 'FINISH_LOADING',
    START_REQUEST : 'START_REQUEST',
    FINISH_REQUEST : 'FINISH_REQUEST'
}


export const AirportTypes = {
    GET_AIRPORTS : 'GET_AIRPORTS',
    REGISTER_AIRPORT : 'REGISTER_AIRPORT',
    UPDATE_AIRPORT : 'UPDATE_AIRPORT',
    DELETE_AIRPORT : 'DELETE_AIRPORT',
    AIRPORT_FEEDBACK : 'AIRPORT_FEEDBACK',
}


export const AirlineTypes = {
    GET_AIRLINES : 'GET_AIRLINES',
    REGISTER_AIRLINE : 'REGISTER_AIRLINE',
    UPDATE_AIRLINE : 'UPDATE_AIRLINE',
    DELETE_AIRLINE : 'DELETE_AIRLINE',
    AIRLINE_FEEDBACK : 'AIRLINE_FEEDBACK',
}


export const FlightTypes = {
    GET_FLIGHTS : 'GET_FLIGHTS',
    REGISTER_FLIGHT : 'REGISTER_FLIGHT',
    UPDATE_FLIGHT : 'UPDATE_FLIGHT',
    DELETE_FLIGHT : 'DELETE_FLIGHT',
    FLIGHT_FEEDBACK : 'FLIGHT_FEEDBACK',
}


export const RunawayTypes = {
    GET_RUNAWAYS : 'GET_RUNAWAYS',
    REGISTER_RUNAWAY : 'REGISTER_RUNAWAY',
    UPDATE_RUNAWAY : 'UPDATE_RUNAWAY',
    DELETE_RUNAWAY : 'DELETE_RUNAWAY',
    RUNAWAY_FEEDBACK : 'RUNAWAY_FEEDBACK',
}